#!/bin/sh /etc/rc.common

USE_PROCD=1

START=90
STOP=10

PROG=/usr/sbin/wzgw

start_service()
{
    procd_open_instance

    procd_set_param command "$PROG"

    # Neustart bei Absturz
    procd_set_param respawn

    # Syslog-Ausgabe übernehmen
    procd_set_param stdout 1
    procd_set_param stderr 1

    procd_close_instance
}

reload_service()
{
    # Konfiguration neu einlesen
    procd_send_signal wzgw HUP
} 
